---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-latest
    image: docker.io/library/ubuntu:latest
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: oraclelinux-8
    image: docker.io/library/oraclelinux:8
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy