---
roles:
  - src: git@github.com:bkotyrev/vector-role.git
    scm: git
    version: "1.0.0"
    name: vector
  - src: git@github.com:bkotyrev/lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.12.1"
    name: clickhouse
