[webservers]
web-1 ansible_host=158.160.63.8 fqdn=web-1.ru-central1.internal
web-2 ansible_host=158.160.58.167 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=158.160.40.51 fqdn=main.ru-central1.internal
replica ansible_host=158.160.41.113 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=93.77.183.186 fqdn=storage.ru-central1.internal
